server:
  port: 8081
  tomcat:
    threads:
      max: 256


spring:
  redis:
    host: localhost
    post: 6379
  kafka:
    bootstrap-servers: localhost:9092

http:
  client:
    connectionTimeout: 3000
    readTimeout: 7000
    maxConnection: 50
    maxConnPerRoute: 10

naver:
  openapi:
    movieUrl: https://openapi.naver.com/v1/search/movie.json


